# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy to Container App

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Solution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Print Secrets
        env:
          SECRET_ONE: ${{ secrets.tenant }}
          SECRET_TWO: ${{ secrets.service_principal }}
          SECRET_THREE: ${{ secrets.service_principal_password }}
          SECRET_FOUR: ${{ secrets.git_access_token }}
        run: |
          echo "Secret 1: $SECRET_ONE"
          echo "Secret 2: $SECRET_TWO"
          echo "Secret 3: $SECRET_THREE"
          echo "Secret 3: $SECRET_FOUR"
          # Add more echo commands for additional secrets as needed

        
      - name: Build and push image
        uses: azure/acr-build@v1
        with:
          tenant: ${{ secrets.tenant }}
          registry: microhackregistry
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          dockerfile: ./Dockerfile
          repository: microhackapp
          image: microhackapp-containerimage
          git_access_token: ${{ secrets.git_access_token }}
          
