# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy to Container App

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Solution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Build and Push Image
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login -u "${{ secrets.ACR_USERNAME }}" --password-stdin microhackregistry.azurecr.io &&
          docker build -t microhackregistry.azurecr.io/microhackapp:1 -f Dockerfile . &&
          docker push microhackregistry.azurecr.io/microhackapp:1
        env:
          DOCKER_USERNAME: ${{ secrets.ACR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image
        uses: azure/acr-build@v1
        with:
          tenant: ${{ secrets.tenant }}
          registry: microhackregistry.azurecr.io
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          dockerfile: ./Dockerfile
          repository: microhackapp
          image: microhackapp-containerimage
          git_access_token: ${{ secrets.git_access_token }}

